### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by vududr8** [vududr8/diary#1]
# About
日頃のタスク全般がここに載る

# Weekly Task
- [ ] Write Article?  
- [ ] Commit Code?  
- [ ] Read OSS Code?(add list?)  
- [ ] Read Book ?(add list?)  
  - [ ] Learning Malware Analysis 4-5  
  - [ ] BlackHat Python  
- [x] make ToDo List?

**Comment by vududr8** [comment]
# Title 🍣 
## About
Template Task
## What/Why 

## Task/ToDo
- [ ] task name  
  - [ ] task name
- [x] task name   

##  Dead Line

**Comment by vududr8** [comment]
# Weekly Task
- [ ] Write Article?  
- [ ] Commit Code?  
- [ ] Read Book ?(also, add book to list?)  
- [ ] make ToDo List?

**Comment by vududr8** [comment]
## August 1st Weekly Task
- [ ] Write A Article About intro to pwn
- [ ] make usage program
- [ ] make simple net tool 
- [ ] Read OSS: One-Lin3r
